name: Deploy Angular to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm ci
        working-directory: ./frontend # <--- IMPORTANT : On dit à GitHub d'aller dans frontend

      - name: Build Angular App
        run: npm run build -- --base-href /combatfit/
        working-directory: ./frontend # <--- IMPORTANT ici aussi

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: frontend/dist/mathias-karate/browser # <--- On a ajouté "frontend/" au début du chemin
          branch: gh-pages